### ISSUE TITLE
(doc) Questions on intro part on tensor

### ISSUE THREAD

**Issue by qlibp** [minitorch/Module-2#1]
The [example](https://minitorch.github.io/tensordata.html#tensor-strides) in this part, have two exact same figs, and it confuses me though I'm kind of knowing what you're talking about.

Also, is that 5 x 2 matrix(5 rows, 2 cols) could have stride (5,1)? It somehow violates your rules at the end which is `one_dim_idx = sum(id_x * stride_x)`

**Comment by srush** [comment]
Yup, looks like this was a bug. Should be fixed on the site now.

**Comment by qlibp** [comment]
> Yup, looks like this was a bug. Should be fixed on the site now. 

Just a brief remind, there is still one small bug. It should point to the 1d list where idx=2

![image](https://user-images.githubusercontent.com/43082379/91750457-b5edd900-ebf5-11ea-8742-e0bf1f9891f8.jpeg)
