### ISSUE TITLE
`count` function in minitorch/tensor_data.py

### ISSUE THREAD

**Issue by Abhimanyu08** [minitorch/Module-2#12]
count function needs to have strides as an argument for tensors which aren't contiguous. Strides will be required in cases where stride can't simply be inferred using shape. for.eg a permuted tensor.

**Comment by srush** [comment]
The count function is poorly named. We are changing it in the next version sorry about that. 

It should just return the indices in "counting" order, i.e. (0, 0, 0), (0, 0, 1), (0, 0, 2) ... 

It is *not* aware of the strides.

**Comment by Abhimanyu08** [comment]
Thanks for the reply. I was thinking of count function as an inverse of `index_to_position` which led me to create this issue.
