### ISSUE TITLE
Task 2.4 required for tests for 2.3

### ISSUE THREAD

**Issue by sebffischer** [minitorch/Module-2#13]
Thanks for the awesome teaching library, I have learned so much already from the amazing design and use of great tools! 

A small suggestion: 
As far as I can tell, the tests for task 2.3 cannot be run without completing at least part of task 2.4 (shape_broadcast). 
Also I think it would be better to do 2.4 before 2.3 because otherwise, it is not clear why backward can also return a tensor that has a different shape than the input tensor.

**Comment by srush** [comment]
Yes! I agree this is a significant point of confusion. I hope that it didn't lead you too far off track. Reworking this section for our class next year.

**Comment by sebffischer** [comment]
Another minor issue at some point was for me that it was not clear from the docs whether the reduce-operations should remove the reduced dimensions or set them to 1 (or whether both cases should be handled depending on which out_shape is passed to tensor_reduce)

**Comment by sebffischer** [comment]
Another thing that caused bugs for me was that shape_broadcast claims that shape1 and shape2 are tuples. 
Maybe this should be changed to (array, tuple) because the ._shape of Tensor (that is e.g. returned by the tuple method) can also be an array. If one e.,g. uses '+' to concatenate tuples this leads to confusing behavior.

**Comment by sebffischer** [comment]
Also, I don't quite understand why the pre-implemented Sum and Mean methods in tensor_functions only accept one integer as the dimension. I think accepting multiple dimensions would be better because: 

1. The function created by reduce in tensor_ops is described as taking dims as a list argument, so the functionality is already implemented anyway.
2. It is more in line with PyTorch

**Comment by sebffischer** [comment]
There also seems to be an ambiguity regarding the reduce function with respect to dimensions that have length 1 but are not to be reduced and those that are to be reduced.

**Comment by srush** [comment]
Thanks. These are all helpful. I am adding the following checks for the next version: 

* Checks that shapes are always tuples
* Code rewrite to ensure that reductions are always on a single axis / dim just like pytorch (pytorch does not take a lists of reduced dims)
* Make it clear that reduced dims are never removed but kept as size 1 (like keepdim)
