### ISSUE TITLE
(doc) Description on iminitorch.broadcast_index is not quite right

### ISSUE THREAD

**Issue by qlibp** [minitorch/Module-2#2]
[here](https://minitorch.github.io/module2.html#minitorch.broadcast_index)
- According to the description, I don't exactly know what to return. `return None` and return through `out_index`? Or I return a `position` which is of type `int`?
- If I need to return through `out_index`, then the description saying that it convert `index` to `position` is not quite right.

**Comment by srush** [comment]
Good catch. This description is out of date. 

You should `return None` and just fill in `out_index`.  The description is wrong the function is to produce an `out_index` which then gets passed to `index_to_position` to produce a position. 

I will update.

**Comment by qlibp** [comment]
> Good catch. This description is out of date.
> 
> You should `return None` and just fill in `out_index`. The description is wrong the function is to produce an `out_index` which then gets passed to `index_to_position` to produce a position.
> 
> I will update.

There're several functions that have unclear return type, eg. `_zip` in `tensor_zip`.

**Comment by srush** [comment]
Updated: https://minitorch.github.io/module2.html#minitorch.broadcast_index

> There're several functions that have unclear return type, eg. _zip in tensor_zip.

These functions all have None return types and write to their out variables. I'll add that to each of them.
