### ISSUE TITLE
Some weird codes need explanation

### ISSUE THREAD

**Issue by qlibp** [minitorch/Module-2#3]
```python
def reduce(fn, start=0.0):
    f = tensor_reduce(fn)

    def ret(a, dims=None, out=None):
        if out is None:
            out_shape = list(a.shape)
            for d in dims:
                out_shape[d] = 1
            # Other values when not sum.
            out = a.zeros(tuple(out_shape))
            out._tensor._storage[:] = start

        diff = len(a.shape) - len(out.shape)        # weird

        reduce_shape = []
        reduce_size = 1
        for i, s in enumerate(a.shape):
            if i < diff or out.shape[i - diff] == 1:
                reduce_shape.append(s)
                reduce_size *= s
            else:
                reduce_shape.append(1)
        assert len(out.shape) == len(a.shape)      # weird
        f(*out.tuple(), *a.tuple(), reduce_shape, reduce_size)
        return out

    return ret
```

Can't understand why we need this two lines? Do you assert that the input and output should have same dimension sizes? Seems that it will pass in shape like `out = (1, )` and `in = (1,1)`

**Comment by srush** [comment]
Yes, this is bad. I think that assert is wrong, because I want to allow broadcasted reductions. However, I don't think they are necessary. 

Are you running into an issue based on this line? Perhaps I will just force `out` to be the same rank as `a`. Users can always call it with a view.

**Comment by qlibp** [comment]
> Are you running into an issue based on this line? Perhaps I will just force `out` to be the same rank as `a`. Users can always call it with a view. 

For now, I personally disabled the assert and it seems better to force the rank to be the same first.

**Comment by srush** [comment]
sounds good. Let me know if you run into as issue.

**Comment by qlibp** [comment]
Another weird code needs explanation:
```python
class Network(minitorch.Module):
    def __init__(self):
        super().__init__()

        # Submodules
        self.layer1 = Linear(2, HIDDEN)
        self.layer2 = Linear(HIDDEN, HIDDEN)
        self.layer3 = Linear(HIDDEN, 1)

    def forward(self, x):
        raise NotImplementedError('Need to include this file from past assignment.')    # weird 
```

I compare with the `class Network` in module 1 and find it's implemented by you and it's obviously not suited here(I mean we can't ctrl-c + ctrl-v to make this work). So, it would be better to just saying that `raise NotImplementedError('Need to implement for Task 2.5.')`

**Comment by srush** [comment]
Good point. Pushed a fix.
